spring:
  application:
    name: iMessage Server
  datasource:
    url: jdbc:mysql://localhost:3306/imessage?characterEncoding=utf8 #
    username:  #
    password:  #
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database:  #
      host:  #
      port:  #
      password:  #
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  mvc:
    async:
      request-timeout: 60000
  mail:
    host:  #
    port:  #
    protocol: smtp
    username:  #
    password:  #
    default-encoding:  #
    properties:
      mail:
        smtp:
          auth:  #
          starttls:
            enable:  #
            required:  #
server:
  port:  #
  servlet:
    session:
      cookie:
        max-age: 2592000
    encoding:
      enabled: true
      charset: UTF-8
      force: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
imessage:
  lowest-allow-client-version: 1
  current-client-version: 1

